In [2]:
import pandas as pd

In [23]:
df = pd.read_csv('Berlin_crimes.csv')
df

,Year,District,Code,Location,Robbery,Street_robbery,Injury,Agg_assault,Threat,Theft,Car,From_car,Bike,Burglary,Fire,Arson,Damage,Graffiti,Drugs,Local
0,2012,Mitte,10111,Tiergarten Süd,70,46,586,194,118,2263,18,328,120,68,16,4,273,26,171,1032
1,2012,Mitte,10112,Regierungsviertel,65,29,474,123,142,3203,10,307,170,37,10,4,380,124,98,870
2,2012,Mitte,10113,Alexanderplatz,242,136,1541,454,304,8988,81,792,822,275,49,27,1538,522,435,3108
3,2012,Mitte,10114,Brunnenstraße Süd,52,25,254,60,66,1916,86,192,396,131,14,5,428,122,213,752
4,2012,Mitte,10221,Moabit West,130,51,629,185,199,2470,94,410,325,161,42,22,516,64,259,1403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2019,Reinickendorf,123012,Nord 2 - Waidmannslust/Wittenau/Lübars,34,19,372,85,123,1160,30,135,150,93,16,3,306,74,110,728
1196,2019,Reinickendorf,123021,MV 1 - Märkisches Viertel,42,22,491,123,187,1100,51,224,76,40,39,19,286,11,73,986
1197,2019,Reinickendorf,123022,MV 2 - Rollbergsiedlung,6,4,84,19,34,293,13,36,18,34,5,2,156,56,21,212
1198,2019,Reinickendorf,123043,West 3 - Borsigwalde/Freie Scholle,8,4,95,18,43,492,21,96,69,38,6,1,79,8,31,218
1199,2019,Reinickendorf,129900,"Bezirk (Rd), nicht zuzuordnen",3,2,14,7,4,59,0,7,15,0,1,0,7,3,9,21

In [61]:
# most crimes are committed in Mitte
base = df.loc[df['District'] == 'Mitte'].sum()
for dis in df.District.unique()[1:]:
    base = pd.concat([base, df.loc[df['District'] == dis].sum()], axis =1)
#base.columns = ['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
CrimeCum = base.drop(['Year','Code','Location', 'District'])
CrimeCum.columns = ['Mitte', 'Friedrichshain-Kreuzberg', 'Pankow', 'Charlottenburg-Wilmersdorf', 'Spandau', 
                   'Steglitz-Zehlendorf', 'Tempelhof-Schöneberg', 'Neukölln', 'Treptow-Köpenick', 'Marzahn-Hellersdorf',
                   'Lichtenberg', 'Reinickendorf']
CrimeCum = CrimeCum.sum()
CrimeCum

Mitte                         727648.0
Friedrichshain-Kreuzberg      522186.0
Pankow                        399058.0
Charlottenburg-Wilmersdorf    469618.0
Spandau                       239582.0
Steglitz-Zehlendorf           243033.0
Tempelhof-Schöneberg          368459.0
Neukölln                      411786.0
Treptow-Köpenick              233173.0
Marzahn-Hellersdorf           227019.0
Lichtenberg                   256785.0
Reinickendorf                 263585.0
dtype: float64

In [62]:
# Inhabitants source: https://de.wikipedia.org/wiki/Verwaltungsgliederung_Berlins
# Mitte has the highest crime rate at 2367 crimes per 10.000 inhabitants on average per year note that this is also a very touristic area
inhab = {'Mitte' : 384172,
        'Friedrichshain-Kreuzberg' : 289762,
        'Pankow' : 407765,
        'Charlottenburg-Wilmersdorf' : 342332,
        'Spandau' : 243997,
        'Steglitz-Zehlendorf' : 308687,
        'Tempelhof-Schöneberg' : 351644,
        'Neukölln' : 329691,
        'Treptow-Köpenick' : 271153,
        'Marzahn-Hellersdorf' : 268548,
        'Lichtenberg' : 291452,
        'Reinickendorf' : 265225}

[[CrimeCum.keys()[i], int(10000/8 * CrimeCum[i] / inhab[CrimeCum.keys()[i]])] for i in range(len(CrimeCum))]

[['Mitte', 2367],
 ['Friedrichshain-Kreuzberg', 2252],
 ['Pankow', 1223],
 ['Charlottenburg-Wilmersdorf', 1714],
 ['Spandau', 1227],
 ['Steglitz-Zehlendorf', 984],
 ['Tempelhof-Schöneberg', 1309],
 ['Neukölln', 1561],
 ['Treptow-Köpenick', 1074],
 ['Marzahn-Hellersdorf', 1056],
 ['Lichtenberg', 1101],
 ['Reinickendorf', 1242]]