In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Berlin_crimes.csv')

In [6]:
df

,Year,District,Code,Location,Robbery,Street_robbery,Injury,Agg_assault,Threat,Theft,Car,From_car,Bike,Burglary,Fire,Arson,Damage,Graffiti,Drugs,Local
0,2012,Mitte,10111,Tiergarten Süd,70,46,586,194,118,2263,18,328,120,68,16,4,273,26,171,1032
1,2012,Mitte,10112,Regierungsviertel,65,29,474,123,142,3203,10,307,170,37,10,4,380,124,98,870
2,2012,Mitte,10113,Alexanderplatz,242,136,1541,454,304,8988,81,792,822,275,49,27,1538,522,435,3108
3,2012,Mitte,10114,Brunnenstraße Süd,52,25,254,60,66,1916,86,192,396,131,14,5,428,122,213,752
4,2012,Mitte,10221,Moabit West,130,51,629,185,199,2470,94,410,325,161,42,22,516,64,259,1403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2019,Reinickendorf,123012,Nord 2 - Waidmannslust/Wittenau/Lübars,34,19,372,85,123,1160,30,135,150,93,16,3,306,74,110,728
1196,2019,Reinickendorf,123021,MV 1 - Märkisches Viertel,42,22,491,123,187,1100,51,224,76,40,39,19,286,11,73,986
1197,2019,Reinickendorf,123022,MV 2 - Rollbergsiedlung,6,4,84,19,34,293,13,36,18,34,5,2,156,56,21,212
1198,2019,Reinickendorf,123043,West 3 - Borsigwalde/Freie Scholle,8,4,95,18,43,492,21,96,69,38,6,1,79,8,31,218
1199,2019,Reinickendorf,129900,"Bezirk (Rd), nicht zuzuordnen",3,2,14,7,4,59,0,7,15,0,1,0,7,3,9,21

In [52]:
base = df.loc[df['Year'] == 2012].sum()
for year in df.Year.unique()[1:]:
    base = pd.concat([base, df.loc[df['Year'] == year].sum()], axis =1)
base.columns = ['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
df2 = base[4:]

In [55]:
df2.transpose()

,Robbery,Street_robbery,Injury,Agg_assault,Threat,Theft,Car,From_car,Bike,Burglary,Fire,Arson,Damage,Graffiti,Drugs,Local
2012,6283,2886,42153,11032,14196,207340,5732,30503,25836,12285,2514,904,48582,11070,11687,101472
2013,6088,3135,41461,10247,14333,220417,6628,35652,26389,11563,2561,972,43176,9573,12746,101063
2014,5583,3228,39190,9515,13733,229955,6629,36032,30434,12149,2322,908,40678,8166,12878,97700
2015,5318,2914,39312,9664,13260,251366,6649,34741,31937,11805,2103,834,39841,8471,15176,100220
2016,5046,2962,41339,10024,13557,251192,7305,34515,34136,11487,2529,1032,41768,9015,14407,100073
2017,4165,2324,42283,10608,13452,220220,6642,32308,30082,8572,2210,872,40985,10428,15503,95027
2018,4202,2417,42828,10656,13965,209957,5671,28677,29978,7568,2334,886,39883,9103,16700,97763
2019,4395,2627,43035,10754,14604,200322,5751,25902,28456,7958,2616,1130,42986,9635,18334,101581